export interface book {
  id: string;
  slug: string;
  title: string;
  description: string;
}

export const books: book[] = [
  {
    id: '1',
    slug: 'book-of-the-iron-frame',
    title: 'Book of the Iron Frame',
    description: '_',
  },
];

export interface doctrine {
  id: string;
  bookId: string;
  slug: string;
  title: string;
  description: string;
}

export const doctrines: doctrine[] = [
  {
    id: '1',
    bookId: '1',
    slug: 'doctrine-of-gravitational-structure',
    title: 'Doctrine of Gravitational Structure',
    description: '_',
  },
  {
    id: '2',
    bookId: '1',
    slug: 'doctrine-of-echoless-frame',
    title: 'Doctrine of Echoless Frame',
    description: '_',
  },
  // {
  //   id: '3',
  //   bookId: '1',
  //   slug: 'doctrine-of-rhythmic-mapping',
  //   title: 'Doctrine of Rhythmic Mapping',
  //   description: '_',
  // },
  // {
  //   id: '4',
  //   bookId: '1',
  //   slug: 'doctrine-of-structural-cognition',
  //   title: 'Doctrine of Structural Cognition',
  //   description: '_',
  // },

  // {
  //   id: '5',
  //   bookId: '1',
  //   slug: 'doctrine-of-doorways',
  //   title: 'Doctrine of Doorways',
  //   description: '_',
  // },
];

export interface codex {
  id: string;
  doctrineId: string;
  slug: string;
  title: string;
  description: string;
  definition?: string;
  governingPrinciple?: string;
  transformationFunction?: string;
  diagnosticQuestions?: string[];
  failureModes?: string[];
  laws?: string[];
  operationalOutputs?: string[];
}

export const codexes: codex[] = [
  {
    id: '1',
    doctrineId: '1',
    slug: 'codex-of-positional-center',
    title: 'Codex of Positional Center',
    description: '_',
    definition:
      'The Codex of Positional Center transforms an undefined or externally positioned structure into one governed by an explicit internal reference point. A positional center is the set of relationships, purposes, responsibilities, and constraints that must remain intact for the structure to remain itself. The positional center is not necessarily a physical location, social position, title, strategy, or method.',
    governingPrinciple:
      'a structure preserves coherence by knowing what remains invariant.',
    transformationFunction:
      'Undefined Structure + Idenfication of Invariants - False Centers = Positional Center.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '2',
    doctrineId: '1',
    slug: 'codex-of-structural-reconfiguration',
    title: 'Codex of Structural Reconfiguration',
    description: '_',
    definition:
      'The Codex of Reconfiguration identifies the source of instability embedded within the internal architecture of a system.',
    governingPrinciple:
      'When instability is generated by the arrangement of components, the arrangement must change.',
    transformationFunction:
      'Coherent Purpose + Inadequate Architecture + Redesign of Components and Relationships.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '3',
    doctrineId: '1',
    slug: 'codex-of-dependency-reduction',
    title: 'Codex of Dependency Reduction',
    description: '_',
    definition:
      'The Codex of Dependency Reduction transforms a structure whose stability depends on unstable external variables into one supported increasingly by invariant, internal, redundant, or replaceable components.',
    governingPrinciple:
      'Stability should depend increasingly on invariant structures and decreasingly on unstable external variables.',
    transformationFunction:
      'load-bearing external variable + dependency identification + substitution, redundancy, removal, or control.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '4',
    doctrineId: '1',
    slug: 'codex-of-gravitational-repositioning',
    title: 'Codex of Gravitational Repositioning',
    description: '_',
    definition:
      'The Codex of Gravitational Repositioning transforms a structure placed in an unfavorable relational, spatial, economic, organizational, or strategic position into one located where its center can be preserved with less force exertion.',
    governingPrinciple:
      'When position makes coherence unnecessarily expensive, change the position before exerting force.',
    transformationFunction:
      'coherent structure + unfavorable position + strategic movement = preserved center with improved leverage.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '5',
    doctrineId: '2',
    slug: 'codex-of-Signal-Evaluation',
    title: 'Codex of Signal Evaluation',
    description: '_',
    definition:
      'The Codex of Signal Evaluation defines the transformation by which incoming influence is evaluated before it is permitted to affect the internal frame.',
    governingPrinciple:
      'No incoming influence modifies the internal frame before it has been evaluated according to evidence rather than charge magnitude.',
    transformationFunction:
      'incoming influence + evaluation = evaluated signal state.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '6',
    doctrineId: '2',
    slug: 'codex-of-Experiment-Design',
    title: 'Codex of Experiment Design',
    description: '_',
    definition:
      'The Codex of Experiment Design defines the transformation by which actions and conditions are deliberately chosen to generate new information.',
    governingPrinciple:
      'Where information is incomplete, create a feedback loop by carefully choosing actions that increase certainty.',
    transformationFunction:
      'ambiguous signal + chosen action + chosen conditions = evaluated signal.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '7',
    doctrineId: '2',
    slug: 'codex-of-role-containment',
    title: 'Codex of Role Containment',
    description: '_',
    definition:
      'The Codex of Role Containment defines the transformation by which a role is defined by the set of responsibilities and obligations it is required to carry.',
    governingPrinciple: 'A coherent role has a defined boundary of influence.',
    transformationFunction:
      'ambiguous scope + role definition = scope clarity.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },

  {
    id: '8',
    doctrineId: '2',
    slug: 'codex-of-proportionate-response',
    title: 'Codex of Proportionate Response',
    description: '_',
    definition:
      'The Codex of Proportionate Response defines the transformation by which incoming stimulus is evaluated, and a minimum amount of necessary response is chosen.',
    governingPrinciple:
      'Response should be calibrated to evidence, consequences, pattern and objective.',
    diagnosticQuestions: [],
    failureModes: [],
    laws: [],
    operationalOutputs: [],
  },
];
